kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name:  {{ .Chart.Name }}-route
spec:
  to:
    kind: Service
    name:  user30-hello-world-svc
    weight: 100
  port:
    targetPort: {{ .Values.containers.containerPort }}