kind: Deployment
apiVersion: apps/v1
metadata:
  name: user30-hello-world-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user30-hello-world
  template:
    metadata:
      labels:
        app: user30-hello-world
    spec:
      containers:
        - name: hello-world
          ports:
            - containerPort: 9999
              protocol: TCP
          image: 'quay.io/sbahar/test-workshop:v5'